# Generated by Django 5.0.1 on 2024-01-26 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zeapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todomodel',
            name='status',
        ),
    ]
