# Generated by Django 5.0.1 on 2024-01-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zeapp', '0002_remove_todomodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='status',
            field=models.IntegerField(choices=[(0, 'A faire'), (1, 'En cours'), (2, 'Terminé'), (3, 'Annulé'), (4, 'En attente'), (5, 'En pause'), (6, 'En attente de validation')], default=2, verbose_name='Status'),
            preserve_default=False,
        ),
    ]
