# Generated by Django 4.2.9 on 2024-03-12 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zeapp', '0003_todomodel_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TodoModel',
            new_name='TaskModel',
        ),
        migrations.AlterModelOptions(
            name='taskmodel',
            options={'ordering': ['-priority'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
    ]
