# Generated by Django 4.2.9 on 2024-03-12 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zeapp', '0004_rename_todomodel_taskmodel_alter_taskmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='duedate',
            field=models.DateField(blank=True, null=True, verbose_name='Due date'),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='priority',
            field=models.IntegerField(blank=True, choices=[(0, 'Faible'), (1, 'Moyen'), (2, 'Elevé'), (3, 'Critique')], null=True, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'A faire'), (1, 'En cours'), (2, 'Terminé'), (3, 'Annulé'), (4, 'En attente'), (5, 'En pause'), (6, 'En attente de validation')], null=True, verbose_name='Status'),
        ),
    ]
