name: Lint, Build, Scan and Test docker image
run-name: ${{github.actor}}-${{github.event_name}}-${{github.sha}}
on: 
    push:
        branches:
            - master
            - dev-*
    pull_request: 
            
jobs:
    
    docker-lint:
        runs-on: ubuntu-latest
        continue-on-error: true
        container:
            image: hadolint/hadolint:2.6.0-alpine
        steps:
            - uses: actions/checkout@v3
            - name: Lint dockerfile
              run: hadolint ./ops/dockers/Dockerfile  

    docker-build:
        runs-on: ubuntu-latest
        needs: "docker-lint"
        steps:
            - uses: actions/checkout@v3
            - name: Build docker image
              run: docker build -t ${{vars.CI_REGISTRY}}:${{github.sha}} -f ops/docker/Dockerfile .
            - name: Save builted image
              run: docker image save -o ${{vars.CI_REGISTRY}}:${{github.sha}}.tar ${{vars.CI_REGISTRY}}:${{github.sha}}
    
    docker-test-build:
        runs-on: ubuntu-letest
        needs: "docker-build"
        steps:
            - uses: actions/checkout@v3
            # - name: Test builed docker image
            #   run: docker run -it -