name: Lint, Build, Scan, Push, Test docker image
run-name: Docker CI/CD
# on:
#   workflow_run:
#     workflows:
#       - Python CI/CD
#     branches:
#       - master
#       - dev-*
#     types:
#       - completed
on: 
    push:
        branches:
            - master
            - dev-*
    pull_request: 
            
jobs:
    
    docker-lint:
        runs-on: ubuntu-latest
        continue-on-error: true
        container:
            image: hadolint/hadolint:2.6.0-alpine
        steps:
            - uses: actions/checkout@v3
            - name: Lint dockerfile
              run: hadolint ./gitops/Dockerfile  

    docker-build:
        runs-on: ubuntu-latest
        needs: "docker-lint"
        steps:
            - uses: actions/checkout@v3
            - name: Build docker image
              run: docker build -t ${{vars.CI_REGISTRY}}:${{github.sha}} -f ./gitops/Dockerfile .
            - name: Docker login
              run: docker login -u ${{secrets.CI_REGISTRY_USER}} -p ${{secrets.CI_REGISTRY_PASSWORD}}
            - name: Docker push image
              run: docker push ${{vars.CI_REGISTRY}}:${{github.sha}}

            # - name: Save builted image
            #   run: docker image save -o ${{github.repository}}:${{github.sha}}.tar ${{vars.CI_REGISTRY}}:${{github.sha}}
    
    docker-test-build:
        runs-on: ubuntu-letest
        needs: "docker-build"
        steps:
            - uses: actions/checkout@v3
            # - name: Test builed docker image
            #   run: docker run -it -