name: Lint, Build, Scan, Push, Test docker image
run-name: Docker CI/CD
on: 
  push:
    branches:
      - master
      - dev-*
  pull_request: 
    branches: [ "master" ]    
jobs:
    
    docker-lint:
        runs-on: ubuntu-latest
        continue-on-error: true
        container:
            image: hadolint/hadolint:2.6.0-alpine
        steps:
            - uses: actions/checkout@v3
            - name: Lint dockerfile
              run: hadolint ./gitops/Dockerfile  

    docker-build:
        runs-on: ubuntu-latest
        needs: "docker-lint"
        steps:
            - uses: actions/checkout@v3
            - name: Build docker image
              run: docker build -t ${{vars.CI_REGISTRY}}:${{github.sha}} -f ./gitops/Dockerfile .
            - name: Save builted image
              run: docker image save -o ${{github.repository}}:${{github.sha}}.tar ${{vars.CI_REGISTRY}}:${{github.sha}}



    docker-scan:
      runs-on: ubuntu-latest
      container: 
        image: cgr.dev/chainguard/grype:0.74.6
      needs: "docker-build"
      steps:
        - uses: actions/checkout@v3
    
    docker-push:
      runs-on: ubuntu-latest
      needs: docker-scan
      steps:
        - uses: actions/checkout@v3
        - name: Docker login
          run: docker login -u ${{secrets.CI_REGISTRY_USER}} -p ${{secrets.CI_REGISTRY_PASSWORD}}
        # - name: Docker push image
        #   run: docker push ${{vars.CI_REGISTRY}}:${{github.sha}}
            